INSERT INTO restaurants(url,
                        image_name,
                        name,
                        genre,
                        tel,
                        open_hours,
                        address,
                        area,
                        comment,
                        takeout_available)
VALUES ('https://tabelog.com/tokyo/A1305/A130501/13206152/',
        '',
        '池袋 一龍庵',
        '居酒屋、寿司、すき焼き',
        '05055952923',
        '【月～土】17:00〜23:30(L.O.22:30)、【定休日】日曜日+不定休',
        '東京都豊島区西池袋3-25-6 清宮ビル1階',
        'ikebukuro',
        '',
        0);

INSERT INTO restaurants(url,
                        image_name,
                        name,
                        genre,
                        tel,
                        open_hours,
                        address,
                        area,
                        comment,
                        takeout_available)
VALUES ('https://tabelog.com/tokyo/A1305/A130501/13149222/',
        '',
        'ダルマ',
        '居酒屋',
        '0359557555',
        '【月.火.木.金.土】18:00〜23:00、【定休日】水曜日・日曜日・祝日',
        '東京都豊島区南池袋2-36-8',
        'ikebukuro',
        '',
        0);
