INSERT INTO restaurants(url,
                        image_name,
                        name,
                        genre,
                        tel,
                        open_hours,
                        address,
                        area,
                        comment,
                        takeout_available)
VALUES ('https://tabelog.com/tokyo/A1305/A130501/13039080/',
        '',
        '魚真',
        '寿司、魚介料理・海鮮料理',
        '0339716324',
        '[月～金] 11:00～14:00 17:30～22:00、[土] 17:30～お客数次第',
        '東京都豊島区東池袋4-3-8',
        'ikebukuro',
        '',
        0);

INSERT INTO restaurants(url,
                        image_name,
                        name,
                        genre,
                        tel,
                        open_hours,
                        address,
                        area,
                        comment,
                        takeout_available)
VALUES ('https://tabelog.com/tokyo/A1305/A130501/13211375/',
        'あまてらす',
        '稲水器 あまてらす （いなみずき あまてらす）',
        '魚介料理・海鮮料理、割烹・小料理、居酒屋',
        '05055951312',
        '[月～土] 18:00～24:00（L.O.23:00）、[日、祝] 18:00～23:00（L.O.22:00）',
        '東京都豊島区東池袋2-62-11',
        'ikebukuro',
        '',
        0);

INSERT INTO restaurants(url,
                        image_name,
                        name,
                        genre,
                        tel,
                        open_hours,
                        address,
                        area,
                        comment,
                        takeout_available)
VALUES ('https://tabelog.com/tokyo/A1305/A130501/13043239/',
        '',
        'たつ家',
        '居酒屋',
        '0339846786',
        '17:00～翌1:00（水曜日定休)',
        '東京都豊島区東池袋1-15-8 フジプラザ 2F',
        'ikebukuro',
        '',
        0);

