INSERT INTO restaurants(id,
                        url,
                        image_name,
                        name,
                        genre,
                        tel,
                        open_hours,
                        address,
                        area,
                        comment,
                        takeout_available)
VALUES (UuidToBin(UUID()),
        'https://tabelog.com/tokyo/A1322/A132201/13225178/',
        '',
        'バシコヤ！！',
        '居酒屋',
        '0359445688',
        '16:30～23:00(L.O.22:30)、[定休日] 土曜日',
        '東京都豊島区上池袋1-26-3 吉田ビル1F',
        'ikebukuro',
        '',
        1);

INSERT INTO restaurants(id,
                        url,
                        image_name,
                        name,
                        genre,
                        tel,
                        open_hours,
                        address,
                        area,
                        comment,
                        takeout_available)
VALUES (UuidToBin(UUID()),
        'https://tabelog.com/tokyo/A1323/A132302/13246002/',
        '',
        'ねぎま',
        '鍋（その他）、割烹・小料理',
        '08087398566',
        '18:00〜22:30、 [定休日] 日曜、月曜、祝日',
        '東京都豊島区北大塚2-31-19 サテライトシティ大塚 B1F',
        'otsuka',
        '',
        0);
