INSERT INTO restaurants(url,
                        image_name,
                        name,
                        genre,
                        tel,
                        open_hours,
                        address,
                        area,
                        comment)
VALUES ('https://tabelog.com/tokyo/A1322/A132201/13105629/',
        '',
        '和可奈',
        '居酒屋、魚介料理・海鮮料理、和食（その他）',
        '0339610717',
        '',
        '東京都板橋区板橋1-10-9',
        'itabashi',
        '');

INSERT INTO restaurants(url,
                        image_name,
                        name,
                        genre,
                        tel,
                        open_hours,
                        address,
                        area,
                        comment)
VALUES ('https://tabelog.com/tokyo/A1322/A132201/13146883/',
        '',
        '馬の串ん',
        '馬肉料理、居酒屋、串焼き',
        '0369035780',
        '[月～木] 17:00～25:00、[金・祝前日] 17:00～25:30、[土] 16:00～25:30、[日・祝] 16:00～24:00',
        '東京都北区滝野川7-2-6 白井ビル 2F',
        'itabashi',
        '');
